jobs:
  - job: compile_and_test_mex
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        mac:
          imageName: macOS-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - task: InstallMATLAB@1
      - task: RunMATLABBuild@1
        inputs:
          tasks: mex test
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      - publish: 'test-results/results.xml'
        artifact: 'test-results-$(imageName)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'toolbox'
          Contents: '**/*.mex*'
          TargetFolder: toolbox/tmpMexFolder
      - publish: 'toolbox/tmpMexFolder' # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines#inputs
        artifact: mex-$(imageName)

  - job: create_and_release_toolbox
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallMATLAB@1
      - task: DownloadPipelineArtifact@2
        inputs:
          itemPattern: 'mex-*/*'
          targetPath: 'tmpMexFolder' # https://github.com/Microsoft/azure-pipelines-tasks/issues/6739
      - task: CopyFiles@2 # Copy mex assets to correct folder 
        inputs:
          SourceFolder: 'tmpMexFolder'
          Contents: '**/*.mex*'
          flattenFolders: true
          targetFolder: 'toolbox'
      - task: RunMATLABBuild@1
        inputs:
          tasks: packageToolbox
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
          
        # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1
      - task: GitHubRelease@1
        inputs:
          # Specifies the name of the GitHub service connection to use to connect to the GitHub repository (OAuth or PAT)
          gitHubConnection: tsharmaMW
          title: "Cross-Platform Array Product Toolbox"
          assets: 'toolbox.mltbx'
          tagSource: 'userSpecifiedTag'
          tag: '$(Build.BuildNumber)'

    dependsOn: compile_and_test_mex