version: 2.1
orbs:
  matlab: mathworks/matlab@dev:8bc1e6ffbe2e10c5f97d0dc42db3c21fdd1abf1a
executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 14.2.0
  windows:
    resource_class: "windows.medium"
    machine:
      image: 'windows-server-2022-gui:current'

jobs:
  build_and_deploy:
    parameters:
      os:
        type: executor
      release:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout

      - matlab/install:
          release: << parameters.release >>
          products: >
            MATLAB_Compiler_SDK
            MATLAB_Test

      # if [[ "<<parameters.os>>" == "windows" ]]; then
      # fi

      # - matlab/run-command:
      #     command: |


      # # Extract and Add MATLAB runtime to PATH for Windows
      # - run:
      #     name: Extract and Add MATLAB runtime to PATH for Windows
      #     command: |
      #         matlab_root=$(matlab -batch "disp(matlabroot)" | tail -n 1 | tr -d '\r')
      #         echo 'export PATH="$matlab_root/runtime/win64:$PATH"' >> $BASH_ENV
      #         export PATH="$matlab_root/runtime/win64:$PATH"
      #         echo "The updated PATH is: $PATH"
          
      # Compiles MATLAB function for deployment
      - matlab/run-command:
          command: |
            mex src/arrayProduct.c;
            addpath(genpath(pwd));
            buildResults = compiler.build.pythonPackage("src/KgToPounds.m", OutputDir = "KgToPoundsPythonBuild");
            save("pythonBuild.mat","buildResults");
            results = runtests("tests/KgToPoundsEquivalenceTest.m");
            assertSuccess(results);

      - store_artifacts:
          path: KgToPoundsPythonBuild

workflows:
  build_and_deploy_python_package:
    jobs:
      - build_and_deploy:
          matrix:
            parameters:
              os: [linux, macos, windows]
              release: ["R2024a", "R2024b"] 