version: 2.1
orbs:
  matlab: mathworks/matlab@dev:8bc1e6ffbe2e10c5f97d0dc42db3c21fdd1abf1a
executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 14.2.0
  windows:
    resource_class: "windows.medium"
    machine:
      image: 'windows-server-2022-gui:current'

jobs:
  build_and_deploy:
    parameters:
      os:
        type: executor
      release:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout

      - matlab/install:
          release: << parameters.release >>
          products: >
            MATLAB_Compiler_SDK
            MATLAB_Test
          
      # Verify if the MATLAB runtime is added to the PATH
      - matlab/run-command:
          command: mcrversion

      - run:
          name: Verify the DLL files exist in MATLAB Runtime directory
          command: |
            found_dll=$(find ${PATH//:/ } -name "mclmcrrt*.dll")
            if [ -n "$found_dll" ]; then
              echo "Found mclmcrrt DLL: $found_dll"
            else
              echo "No mclmcrrt DLL found in PATH."
              exit 1
            fi
          shell: bash

      - run:
          name: Verify MATLAB runtime in PATH
          command: |
            echo "$(which mwregsvr)"
            set -e
            if [[ "${PATH}" == *"runtime"* ]]; then
              echo "MATLAB Runtime is correctly set in PATH."
            else
              echo "MATLAB Runtime is NOT set in PATH."
              exit 1
            fi

      - matlab/run-command:
          command: |
            mex src/arrayProduct.c;
            addpath(genpath(pwd));
            buildResults = compiler.build.pythonPackage("src/KgToPounds.m", OutputDir = "KgToPoundsPythonBuild");
            save("pythonBuild.mat","buildResults");
            results = runtests("tests/KgToPoundsEquivalenceTest.m");
            assertSuccess(results);

      - store_artifacts:
          path: KgToPoundsPythonBuild

workflows:
  build_and_deploy_python_package:
    jobs:
      - build_and_deploy:
          matrix:
            parameters:
              os: [linux, macos, windows]
              release: ["R2024a", "R2024b"] 