version: 2.1
orbs:
  matlab: mathworks/matlab@dev:8bc1e6ffbe2e10c5f97d0dc42db3c21fdd1abf1a
executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 14.2.0
  windows:
    resource_class: "windows.medium"
    machine:
      image: 'windows-server-2022-gui:current'

jobs:
  build_and_deploy:
    parameters:
      os:
        type: executor
      release:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout

      - matlab/install:
          release: << parameters.release >>
          # products: >
          #   MATLAB_Compiler_SDK
          #   MATLAB_Test
          
      # Verify if the MATLAB runtime is added to the PATH
      - matlab/run-command:
          command: mcrversion

      - run:
          name: Verify MATLAB Runtime libraries in PATH
          command: |
            os=$(uname)
            if [[ $os == CYGWIN* || $os == MINGW* || $os == MSYS* ]]; then
              found_dll=$(where mclmcrrt*.dll 2>/dev/null)
            else
              found_dll=$(find ${PATH//:/ } -name "mclmcrrt*.dll" 2>/dev/null)
            fi

            if [ -n "$found_dll" ]; then
              echo "MATLAB Runtime is correctly set in PATH. Found mclmcrrt DLL: $found_dll"
            else
              echo "No mclmcrrt DLL found in PATH. Verify MATLAB Runtime is added to PATH."
              exit 1
            fi
          shell: bash

      # - matlab/run-command:
      #     command: |
      #       mex src/arrayProduct.c;
      #       addpath(genpath(pwd));
      #       buildResults = compiler.build.pythonPackage("src/KgToPounds.m", OutputDir = "KgToPoundsPythonBuild");
      #       save("pythonBuild.mat","buildResults");
      #       results = runtests("tests/KgToPoundsEquivalenceTest.m");
      #       assertSuccess(results);

      # - store_artifacts:
      #     path: KgToPoundsPythonBuild

workflows:
  build_and_deploy_python_package:
    jobs:
      - build_and_deploy:
          matrix:
            parameters:
              os: [linux, macos, windows]
              release: ["R2024a", "R2024b"] 