name: Build and Deploy MATLAB standalone applications
 
on:
  push:
    branches: [ integrateGenerateExecutable ]
 
  workflow_dispatch:
 
# Utilizes repository-stored secrets for MATLAB's batch-token licensing
env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}
 
jobs:
  # This workflow contains a single job called "build-and-upload"
  build-and-upload:
     
    # A job will run for all combinations of OS and release present in the matrix
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        release: [R2024a, R2024b]
 
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
 
    steps:
      - uses: actions/checkout@v3
       
      # Sets up MATLAB on the GitHub Actions runner using setup-matlab@v2 and download MATLAB_Compiler_SDK
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}
          products: >
            MATLAB_Compiler_SDK
            MATLAB_Test

      # Installs Python and add it to the Path
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'

      - name: Compile
        uses: matlab-actions/run-command@v2
        with:
          command: |
            ver;

      - name: Extract and Set MATLAB Runtime Path
        id: set-runtime-path
        uses: matlab-actions/run-command@v2
        with:
          command: |
            matlabRoot = matlabroot;
            runtimePath = fullfile(matlabRoot, 'runtime');
            fprintf('::set-output name=runtimePath::%s\n', runtimePath);

      - name: Verify MATLAB Runtime Directory
        run: |
          runtimePath="${{ steps.set-runtime-path.outputs.runtimePath }}"

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            # PowerShell syntax for Windows
            echo "Runtime Path: ${runtimePath}"
            echo "Contents of ${runtimePath}"
            ls -la "${runtimePath}"
          else
            # Bash syntax for Linux and macOS
            echo "Runtime Path: $runtimePath"
            echo "Contents of $runtimePath:"
            ls -la "$runtimePath"
          fi
        shell: bash

      - name: List MATLAB Runtime Directory
        run: |
          runtimePath="${{ steps.set-runtime-path.outputs.runtimePath }}"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            # PowerShell syntax for Windows
            runtimePath="${runtimePath}\\win64"
            echo "Runtime Path: ${runtimePath}"
            if [ -d "${runtimePath}" ]; then
              echo "Contents of ${runtimePath}"
              ls -la "${runtimePath}"
            else
              echo "Directory $runtimePath does not exist."
              exit 1
            fi
          else
            # Bash syntax for Linux and macOS
            
            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
              runtimePath="${runtimePath}/glnxa64"
            elif [ "${{ matrix.os }}" == "macos-latest" ]; then
              runtimePath="${runtimePath}/maca64"
            fi
            echo "Runtime Path: $runtimePath"
            if [ -d "$runtimePath" ]; then
              echo "Contents of $runtimePath:"
              ls -la "$runtimePath"
            else
              echo "Directory $runtimePath does not exist."
              exit 1
            fi
          fi
        shell: bash

      - name: Add MATLAB runtime to PATH for Windows
        if: matrix.os == 'windows-latest'
        run: |
          $runtimePath = "${{ steps.set-runtime-path.outputs.runtimePath }}\win64"
          [System.IO.File]::AppendAllText("$env:GITHUB_ENV", "`nPATH=$env:PATH;$runtimePath`n")
          Write-Host "Updated PATH: $env:PATH"
        shell: pwsh

      - name: Verify Updated PATH
        run: |
          echo $PATH
        shell: bash
 
      # Compiles MATLAB function for deployment
      - name: Compile
        uses: matlab-actions/run-command@v2
        with:
          command: |
            pyenv
            mex src/arrayProduct.c
            addpath(genpath(pwd))
            KgToPounds([1,2,3,4,5]);
            buildResults = compiler.build.pythonPackage("src/KgToPounds.m", OutputDir = "KgToPoundsPythonBuild");
            save("pythonBuild.mat","buildResults");
            
      # runtests("tests/KgToPoundsEquivalenceTest.m");

      - name: Compile
        uses: matlab-actions/run-command@v2
        with:
          command: ls;

      # For the below test, would have to change python build to ../pythonBuild in test
      - name: Run equivalence tests
        uses: matlab-actions/run-tests@v2
        with:
          select-by-tag: EquivalenceTest
          source-folder: ../
            
      # compiler.build.standaloneApplication("src/KgToPounds.m");

      # Uploads the generated executable as an artifact to GitHub
      - name: Upload generated binary
        uses: actions/upload-artifact@v3
        with:
          name: KgToPounds-${{ matrix.release }}-${{ matrix.os }}
          path: KgToPounds*