# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ generateExecutable ]
  pull_request:
    branches: [ generateExecutable ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MATHWORKS_TOKEN: Chg9cB5H9rXkEQ9/ZXr7LYLOLFOHn91r9VLOjMp8JHDsr1BrvaMKREZ8c2XhuUaK1glRNH1FDU+vdlKAi8rSOklS3Pv5eGp6BS7yEh4Oc+ZnSOLb3fxMHDkKh6PNUzlYt3zYiM7VVmQGuQHJI+5kMg==
  MATHWORKS_ACCOUNT: kapilg@mathworks.com

jobs:
  # This workflow contains a single job called "build"
  build:

    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          products: MATLAB_Compiler_SDK

      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: listVer createExecutable
