name: Compile and Release Executables

on:
  push:
    branches: [ generateExecutable ]
  pull_request:
    branches: [ generateExecutable ]

  workflow_dispatch:

env:
  MATHWORKS_TOKEN: ${{secrets.MATHWORKS_TOKEN}}
  MATHWORKS_ACCOUNT: ${{secrets.MATHWORKS_ACCOUNT}}

jobs:
  build-and-release:

    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-latest, macos-12]
        # release: [R2023a, R2023b]
        os: [macos-12]
        release: [R2023b]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.release }}
          products: MATLAB_Compiler_SDK

      - name: Compile
        uses: matlab-actions/run-command@v1
        with:
          command: mcc -m code/quadraticSolver.m;

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "${{ matrix.os }}-${{ matrix.release }}"
          prerelease: false
          title: "Binary-${{ matrix.os }}-${{ matrix.release }}"
          files: ./quadraticSolver*